language: python
python:
- 2.7
sudo: false

env:
  - TEST_DIR=tests CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython ipython nose sphinx ;
    else
      conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython ipython nose sphinx ;
    fi
  - pip install -r requirements.txt

script:
  - nosetests $TEST_DIR

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_69967e53c837_key -iv $encrypted_69967e53c837_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d;
      tar -xzf credentials.tar.gz ;
      GAE_PYTHONPATH=${HOME}/.cache/google_appengine ;
      export PATH=$PATH:${HOME}/google-cloud-sdk/bin ;
      export PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} ;
      python _ext/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}") ;
      if [ ! -d ${HOME}/google-cloud-sdk ]; then
         curl https://sdk.cloud.google.com | bash;
      fi ;
      gcloud auth activate-service-account --key-file credentials/client-secret.json ;
      gcloud config set project emgeosci ;
      gcloud -q components update gae-python ;
      gcloud -q preview app deploy ./app.yaml --version ${TRAVIS_COMMIT} --promote;
    fi

notifications:
  email:
  - lindseyheagy@gmail.com
